name: tonatona-scotty
version: 0.1.0.0
github: 'lettenj61/tonatona-scotty'
license: BSD3
author: 'Hideyuki Ueno (lettenj61)'
maintainer: 'letitscalable+git@gmail.com'
copyright: '2022 Hideyuki Ueno (lettenj61)'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/tonatona-scotty#readme>

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - data-default >= 0.7 && < 0.8
  - exceptions >= 0.8 && < 0.11
  - http-types >= 0.12 && < 0.13
  - monad-logger >= 0.3 && < 0.4
  - rio >= 0.1 && < 0.2
  - scotty >= 0.12 && < 0.13
  - tonaparser >= 0.1 && < 0.2
  - tonatona >= 0.1 && < 0.2
  - tonatona-logger >= 0.1 && < 0.3
  - wai >= 3.0.0 && < 3.3
  - wai-extra >= 3.0.0 && < 3.2
  - warp >= 3.0.13 && < 3.4

library:
  source-dirs: src

tests:
  tonatona-scotty-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tonatona-scotty
